// Country to currency mapping
export const countryCurrencyMap: Record<string, { code: string; symbol: string; name: string }> = {
  'IN': { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  'US': { code: 'USD', symbol: '$', name: 'US Dollar' },
  'GB': { code: 'GBP', symbol: '£', name: 'British Pound' },
  'EU': { code: 'EUR', symbol: '€', name: 'Euro' },
  'CA': { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  'AU': { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  'JP': { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  'CN': { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  'AE': { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  'SG': { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  'MY': { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  'TH': { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  'ID': { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  'PH': { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  'VN': { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
  'BD': { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  'PK': { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  'LK': { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee' },
  'NZ': { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  'ZA': { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  'BR': { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  'MX': { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
  'AR': { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
  'CL': { code: 'CLP', symbol: '$', name: 'Chilean Peso' },
  'CO': { code: 'COP', symbol: '$', name: 'Colombian Peso' },
  'PE': { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol' },
  'NG': { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  'KE': { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  'EG': { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
  'SA': { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
  'IL': { code: 'ILS', symbol: '₪', name: 'Israeli Shekel' },
  'TR': { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  'RU': { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  'KR': { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  'HK': { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  'TW': { code: 'TWD', symbol: 'NT$', name: 'Taiwan Dollar' },
}

export const countries = [
  { code: 'IN', name: 'India' },
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'EU', name: 'European Union' },
  { code: 'CA', name: 'Canada' },
  { code: 'AU', name: 'Australia' },
  { code: 'JP', name: 'Japan' },
  { code: 'CN', name: 'China' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'SG', name: 'Singapore' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'TH', name: 'Thailand' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'PH', name: 'Philippines' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'AR', name: 'Argentina' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Colombia' },
  { code: 'PE', name: 'Peru' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'KE', name: 'Kenya' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'IL', name: 'Israel' },
  { code: 'TR', name: 'Turkey' },
  { code: 'RU', name: 'Russia' },
  { code: 'KR', name: 'South Korea' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'TW', name: 'Taiwan' },
]

export function getCurrencyByCountry(countryCode: string) {
  return countryCurrencyMap[countryCode] || countryCurrencyMap['IN'] // Default to INR
}

export function formatCurrency(amount: number, currencyCode: string = 'INR') {
  const currency = Object.values(countryCurrencyMap).find(c => c.code === currencyCode) || countryCurrencyMap['IN']
  return `${currency.symbol}${amount.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

